version: '3.3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: --storageEngine wiredTiger
    volumes:
       - mongovolume:/data/mongo
  messaging:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  search:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  graph:
    image: neo4j:3.0
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - graphdatavolume:/data
      - graphlogsvolume:/logs
volumes:
  mongovolume:
  graphdatavolume:
  graphlogsvolume: